/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculator.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
calculate_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		int_inputs add_1_arg;
		int_inputs sub_1_arg;
		int_inputs mul_1_arg;
		int_inputs div_1_arg;
		int_inputs sub_v2_nonnegative_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case ADD:
		_xdr_argument = (xdrproc_t) xdr_int_inputs;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) add_1_svc;
		break;

	case SUB:
		_xdr_argument = (xdrproc_t) xdr_int_inputs;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) sub_1_svc;
		break;

	case MUL:
		_xdr_argument = (xdrproc_t) xdr_int_inputs;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) mul_1_svc;
		break;

	case DIV:
		_xdr_argument = (xdrproc_t) xdr_int_inputs;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) div_1_svc;
		break;

	case SUB_v2_NONnegative:
		_xdr_argument = (xdrproc_t) xdr_int_inputs;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) sub_v2_nonnegative_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
calculate_prog_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		float_inputs fadd_2_arg;
		float_inputs fsub_2_arg;
		float_inputs fmul_2_arg;
		float_inputs fdiv_2_arg;
		float_inputs fsub_v2_nonnegative_2_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case FADD:
		_xdr_argument = (xdrproc_t) xdr_float_inputs;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) fadd_2_svc;
		break;

	case FSUB:
		_xdr_argument = (xdrproc_t) xdr_float_inputs;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) fsub_2_svc;
		break;

	case FMUL:
		_xdr_argument = (xdrproc_t) xdr_float_inputs;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) fmul_2_svc;
		break;

	case FDIV:
		_xdr_argument = (xdrproc_t) xdr_float_inputs;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) fdiv_2_svc;
		break;

	case FSUB_v2_NONnegative:
		_xdr_argument = (xdrproc_t) xdr_float_inputs;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) fsub_v2_nonnegative_2_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CALCULATE_PROG, INT_CALCULATE_VER);
	pmap_unset (CALCULATE_PROG, FLOAT_CALCULATE_VER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULATE_PROG, INT_CALCULATE_VER, calculate_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULATE_PROG, INT_CALCULATE_VER, udp).");
		exit(1);
	}
	if (!svc_register(transp, CALCULATE_PROG, FLOAT_CALCULATE_VER, calculate_prog_2, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULATE_PROG, FLOAT_CALCULATE_VER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULATE_PROG, INT_CALCULATE_VER, calculate_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULATE_PROG, INT_CALCULATE_VER, tcp).");
		exit(1);
	}
	if (!svc_register(transp, CALCULATE_PROG, FLOAT_CALCULATE_VER, calculate_prog_2, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULATE_PROG, FLOAT_CALCULATE_VER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
