/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATOR_H_RPCGEN
#define _CALCULATOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct int_inputs {
	int num1;
	int num2;
	char operator;
};
typedef struct int_inputs int_inputs;

struct float_inputs {
	float num1;
	float num2;
	char operator;
};
typedef struct float_inputs float_inputs;

#define CALCULATE_PROG 0x31415926
#define INT_CALCULATE_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  int * add_1(int_inputs *, CLIENT *);
extern  int * add_1_svc(int_inputs *, struct svc_req *);
#define SUB 2
extern  int * sub_1(int_inputs *, CLIENT *);
extern  int * sub_1_svc(int_inputs *, struct svc_req *);
#define MUL 3
extern  int * mul_1(int_inputs *, CLIENT *);
extern  int * mul_1_svc(int_inputs *, struct svc_req *);
#define DIV 4
extern  int * div_1(int_inputs *, CLIENT *);
extern  int * div_1_svc(int_inputs *, struct svc_req *);
#define SUB_v2_NONnegative 5
extern  int * sub_v2_nonnegative_1(int_inputs *, CLIENT *);
extern  int * sub_v2_nonnegative_1_svc(int_inputs *, struct svc_req *);
extern int calculate_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  int * add_1();
extern  int * add_1_svc();
#define SUB 2
extern  int * sub_1();
extern  int * sub_1_svc();
#define MUL 3
extern  int * mul_1();
extern  int * mul_1_svc();
#define DIV 4
extern  int * div_1();
extern  int * div_1_svc();
#define SUB_v2_NONnegative 5
extern  int * sub_v2_nonnegative_1();
extern  int * sub_v2_nonnegative_1_svc();
extern int calculate_prog_1_freeresult ();
#endif /* K&R C */
#define FLOAT_CALCULATE_VER 2

#if defined(__STDC__) || defined(__cplusplus)
#define FADD 1
extern  float * fadd_2(float_inputs *, CLIENT *);
extern  float * fadd_2_svc(float_inputs *, struct svc_req *);
#define FSUB 2
extern  float * fsub_2(float_inputs *, CLIENT *);
extern  float * fsub_2_svc(float_inputs *, struct svc_req *);
#define FMUL 3
extern  float * fmul_2(float_inputs *, CLIENT *);
extern  float * fmul_2_svc(float_inputs *, struct svc_req *);
#define FDIV 4
extern  float * fdiv_2(float_inputs *, CLIENT *);
extern  float * fdiv_2_svc(float_inputs *, struct svc_req *);
#define FSUB_v2_NONnegative 5
extern  float * fsub_v2_nonnegative_2(float_inputs *, CLIENT *);
extern  float * fsub_v2_nonnegative_2_svc(float_inputs *, struct svc_req *);
extern int calculate_prog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FADD 1
extern  float * fadd_2();
extern  float * fadd_2_svc();
#define FSUB 2
extern  float * fsub_2();
extern  float * fsub_2_svc();
#define FMUL 3
extern  float * fmul_2();
extern  float * fmul_2_svc();
#define FDIV 4
extern  float * fdiv_2();
extern  float * fdiv_2_svc();
#define FSUB_v2_NONnegative 5
extern  float * fsub_v2_nonnegative_2();
extern  float * fsub_v2_nonnegative_2_svc();
extern int calculate_prog_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_int_inputs (XDR *, int_inputs*);
extern  bool_t xdr_float_inputs (XDR *, float_inputs*);

#else /* K&R C */
extern bool_t xdr_int_inputs ();
extern bool_t xdr_float_inputs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATOR_H_RPCGEN */
